#!/usr/bin/env zsh -i

# Auto-generated by Voodoo
# First-time script for project setup (DELETE ME AFTER RUNNING!)
# Now using python3.7

DOCS_DIR=~/dev/githubdocs

print Setting up your virtualenv

mkdir env
python -m venv env

print Activating environment
source env/bin/activate

if [ $? -ne 0 ]; then
    print Making circuitbrew Virtual env and activating failed
    exit -1
fi

print Working in virtualenv circuitbrew


# Set up the pip packages
pip install pytest mock pytest-cov python-coveralls coverage sphinx tox restview schema docopt
#pip install sphinx restview
#echo "cd ~/dev/circuitbrew" >> ~/dev/envs/circuitbrew/bin/postactivate
#echo "unset PYTHONPATH" >> ~/dev/envs/circuitbrew/bin/postactivate

# Start python develop
python setup.py develop

# Initialize the git repo
github_remote='git@github.com:virantha/circuitbrew.git'
git init
git remote add origin $github_remote
git add .
git commit -am "Setting up new project circuitbrew"

# Prompt if we want to push to remote git
read -q "REPLY?Create remote repository at $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    #curl --data '{"name":"circuitbrew", "description":""}' --user "virantha" https://api.github.com/user/repos
    gh auth login
    gh repo create -d "" --public circuitbrew
fi

read -q "REPLY?Push to remote repository $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    git push -u origin main
fi

print
# Create the docs repository
current_dir=`pwd`
read -q "REPLY?Create and push docs to $github_remote [y/N]?"
if [[  $REPLY == y ]]; then
    # Go to the docs build dir, and check out our repo
    cd $DOCS_DIR
    git clone https://github.com/virantha/circuitbrew.git
    cd circuitbrew
    git checkout --orphan gh-pages
    git rm -rf .

    cd $current_dir/docs
    pip install sphinx sphinx-readble-theme
    make html
    cd $DOCS_DIR
    cd circuitbrew
    touch .nojekyll
    git add .
    git commit -m "docs"
    git push origin gh-pages

fi
