site_name: CircuitBrew
repo_url: https://github.com/virantha/CircuitBrew
theme:
  name: "material"

  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

plugins:
  - search
  - autorefs
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:  
  - Home: index.md
  - Usage guide:
      - 'Generating netlists': usage/generating.md
      - 'Writing circuits': usage/writing.md
      - Examples:
          - Inverter: usage/examples/inverter.md
      - 'Techfiles': usage/techfiles.md
  - API: 
      - Module: api/api_module.md
      - Ports: api/api_ports.md